const UNITS = [
  {
    id: 1,
    icon: "🧔",
    class: "warrior",
    name: "Thorin",
    health: 100,
    damage: 1,
    price: 500,
    type: "player",
    inventory: [],
  },
  {
    id: 2,
    icon: "👩‍🎤",
    class: "warrior",
    name: "Athena",
    health: 120,
    damage: 1,
    price: 550,
    type: "player",
    inventory: [],
  },
  {
    id: 3,
    icon: "🧑‍🚀",
    class: "warrior",
    name: "Bjorn",
    health: 110,
    damage: 1,
    price: 520,
    type: "player",
    inventory: [],
  },
  {
    id: 4,
    icon: "👩‍⚖️",
    class: "archer",
    name: "Luna",
    health: 80,
    damage: 1,
    price: 450,
    type: "player",
    inventory: [],
  },
  {
    id: 5,
    icon: "🧑‍🦳",
    class: "archer",
    name: "Elyan",
    health: 85,
    price: 480,
    damage: 1,
    type: "player",
    inventory: [],
  },
  {
    id: 6,
    icon: "👨‍🏫",
    class: "archer",
    name: "Robin",
    health: 90,
    price: 470,
    damage: 1,
    type: "player",
    inventory: [],
  },
  {
    id: 7,
    icon: "👩‍⚕️",
    class: "healer",
    name: "Serena",
    health: 70,
    price: 400,
    damage: 1,
    type: "player",
    inventory: [],
  },
  {
    id: 8,
    icon: "🧑‍⚕️",
    class: "healer",
    name: "Aldric",
    health: 75,
    price: 420,
    damage: 1,
    type: "player",
    inventory: [],
  },
  {
    id: 9,
    icon: "👨‍🎨",
    class: "healer",
    name: "Lyra",
    health: 65,
    price: 390,
    damage: 1,
    type: "player",
    inventory: [],
  },
  {
    id: 10,
    icon: "👨‍🚀",
    class: "warrior",
    name: "Kane",
    health: 115,
    price: 530,
    damage: 1,
    type: "player",
    inventory: [],
  },
  {
    id: 11,
    icon: "🧑‍🎤",
    class: "archer",
    name: "Faye",
    health: 88,
    damage: 1,
    price: 460,
    type: "player",
    inventory: [],
  },
  {
    id: 12,
    icon: "🧑‍⚖️",
    class: "healer",
    name: "Merlin",
    health: 72,
    damage: 1,
    price: 410,
    type: "player",
    inventory: [],
  },
  {
    id: 13,
    icon: "👨‍🎤",
    class: "warrior",
    name: "Drake",
    health: 130,
    damage: 1,
    price: 600,
    type: "player",
    inventory: [],
  },
  {
    id: 14,
    icon: "🧑‍🏫",
    class: "archer",
    name: "Elara",
    damage: 1,
    health: 92,
    price: 490,
    type: "player",
    inventory: [],
  },
  {
    id: 15,
    icon: "👩‍🚀",
    class: "healer",
    name: "Gwen",
    damage: 1,
    health: 78,
    price: 430,
    type: "player",
    inventory: [],
  },
];

const ENEMIES = [
  {
    icon: "🐺",
    health: 80,
    damage: 15,
    reward: 100,
    type: "enemy",
  },
  {
    icon: "🦁",
    health: 120,
    damage: 25,
    reward: 150,
    type: "enemy",
  },
  {
    icon: "🐍",
    health: 60,
    damage: 10,
    reward: 80,
    type: "enemy",
  },
  {
    icon: "🐗",
    health: 100,
    damage: 20,
    reward: 120,
    type: "enemy",
  },
  {
    icon: "🦇",
    health: 50,
    damage: 8,
    reward: 70,
    type: "enemy",
  },
  {
    icon: "🦖",
    health: 150,
    damage: 30,
    reward: 200,
    type: "enemy",
  },
  {
    icon: "🦂",
    health: 70,
    damage: 12,
    reward: 90,
    type: "enemy",
  },
  {
    icon: "🐉",
    health: 200,
    damage: 35,
    reward: 250,
    type: "enemy",
  },
  {
    icon: "🦅",
    health: 90,
    damage: 18,
    reward: 110,
    type: "enemy",
  },
  {
    icon: "🐊",
    health: 110,
    damage: 22,
    reward: 140,
    type: "enemy",
  },
  {
    icon: "🐻",
    health: 130,
    damage: 28,
    reward: 170,
    type: "enemy",
  },
  {
    icon: "🦊",
    health: 75,
    damage: 14,
    reward: 95,
    type: "enemy",
  },
  {
    icon: "🐉",
    health: 180,
    damage: 33,
    reward: 220,
    type: "enemy",
  },
  {
    icon: "🦈",
    health: 160,
    damage: 32,
    reward: 210,
    type: "enemy",
  },
  {
    icon: "🦢",
    health: 85,
    damage: 16,
    reward: 100,
    type: "enemy",
  },
];

export { UNITS, ENEMIES };
